# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
    default:
    - step:
       script:
        - apt-get update
        - apt-get -qq install git-ftp
        - git ftp init -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_URL